travis:
  secure:
    BINSTAR_TOKEN: NoDRVMHn4+BTWagNbqXJ8OxKVdgb/2y14tk4DhKYddwWAv3GgSdEnok0zTRvI7E6hbYZ0kpIEPmAUopGhcC5B8wAwsmqVgxILrQ5t9T7EHufs4R1d2ypUf693zyJmabkmrOKbS0ngHx94ms0QXH9t8NEcUtoAGFBQq46Szl+GZLaBSyNIIQsR7P5jyJC3LGdMBp+yZ7mebPuoZmD7vdIJMPh0Wm+/9OyczlHYDjm5jb2s3cXC360WvR1eEI5WOH0piZP27jPanBO0O0aFQdDwjr4TF6EF+fHEx56E6uSIM3J0jjOZQ0X3j9dT3gDYcBjjQT/ojyfTm9Bd18ETpfTe7W3M3qO3Q8s4KGgtVkZmAsqSR+DkO0G1SUKGqF0dBfwV0R3Jg2LcC6Cpih0sZhi/Db4ugBSvjkRATrxq4dW6jBmGazVjo9ccgGgHke4tDZiJHroKgqDzwZLJLgBNgmIL/qP4yJ1gUWTTNEfOBTd8bUmJEkOXe6XIG8bl82Tc5TLQm5PsqfudevDZrM83jsqVMARhUKX3mkKzX9Fj9QifAEUTUQ3Yif6KWSqMMs0BuEi6PjYraMseyIX+Kdueq+aB+ba3UwMGtHuN53ukdiOlRf0UY+r5tCSB3DX+4D9+oMTvb0wK/bMRJeyw6pdRF7czmKuzUfoFmdxfC6W1NtGD2w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
